name: youcandoit
favicon: null
layout_spectrum: 0.1879144199192524
typography_spectrum: 0.3164968122728169
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.2319702038075775
  lightness: 0.3999998327344656
  saturation: 0.9537746312562376
  rhythmicContrast: 0.5086529010441154
purpose: []
